# Generated by Django 3.2.13 on 2022-08-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser',
            name='account_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('suspended', 'Suspended')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='daily_target',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='level',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('supervisor', 'Supervisor'), ('administrator', 'Administrator')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='monthly_target',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
