# Generated by Django 3.2.13 on 2022-08-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_crm', '0002_auto_20220809_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='amount_paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
