# Generated by Django 3.2.13 on 2022-08-10 07:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection_crm', '0003_alter_survey_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='account_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='level',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('supervisor', 'Supervisor'), ('administrator', 'Administrator')], default='agent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='systems_access',
            field=models.CharField(blank=True, choices=[('crm_and_telephony', 'CRM and Telephony'), ('crm_only', 'CRM Only'), ('telephony_only', 'Telephony Only')], default='crm_and_telephony', max_length=255, null=True),
        ),
    ]
