# Generated by Django 2.2.18 on 2021-02-11 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendServerManagerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=253)),
                ('port', models.CharField(max_length=10)),
                ('server_type', models.CharField(choices=[('asterisk', 'Asterisk'), ('freeswitch', 'Freeswitch')], default='asterisk', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='hotdesk',
            name='backend_manager_config',
            field=models.ForeignKey(blank=True, help_text='Backend Manager Config', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpline.BackendServerManagerConfig'),
        ),
    ]
