# Generated by Django 2.2.18 on 2021-02-16 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0002_auto_20210211_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='disposition_choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
