# Generated by Django 2.2.18 on 2021-02-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0004_auto_20210216_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincdr',
            name='hl_queue',
            field=models.CharField(max_length=100),
        ),
    ]
