# Generated by Django 2.2.18 on 2021-02-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0005_auto_20210218_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincdr',
            name='hl_queue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
