# Generated by Django 2.2.18 on 2021-03-30 16:48

from django.db import migrations, models
import helpline.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0007_auto_20210223_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='sipserverconfig',
            name='webrtc_gateway_url',
            field=models.URLField(default=helpline.models.webrtc_gateway_url_default),
        ),
    ]
