# Generated by Django 2.2.18 on 2021-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0010_auto_20210504_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=45, null=True)),
                ('comment', models.CharField(blank=True, max_length=80, null=True)),
                ('prefix', models.CharField(blank=True, max_length=5, null=True)),
                ('hotdesk', models.ManyToManyField(blank=True, related_name='did_assigned_hotdesks', to='helpline.Hotdesk')),
            ],
        ),
    ]
