# Generated by Django 2.2.25 on 2022-03-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0013_service_backend_manager_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='extension',
            field=models.CharField(help_text='Extension callers will dial e.g 116.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('extension', 'backend_manager_config')},
        ),
    ]
