# Generated by Django 2.2.25 on 2022-05-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0014_auto_20220320_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdesk',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='primary'),
        ),
    ]
