# Generated by Django 3.2.13 on 2022-07-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0017_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendservermanagerconfig',
            name='mysql_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backendservermanagerconfig',
            name='mysql_user',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
