# Generated by Django 3.2.13 on 2022-07-01 21:49

from django.db import migrations, models
import helpline.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0018_auto_20220701_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendservermanagerconfig',
            name='webhook_url',
            field=models.URLField(default=helpline.models.webhook_url_default),
        ),
    ]
