# Generated by Django 3.2.13 on 2022-08-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0019_backendservermanagerconfig_webhook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendservermanagerconfig',
            name='mysql_password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='backendservermanagerconfig',
            name='mysql_user',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
