# Generated by Django 3.2.13 on 2022-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0019_backendservermanagerconfig_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='backendservermanagerconfig',
            name='mysql_host',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='backendservermanagerconfig',
            name='mysql_port',
            field=models.IntegerField(blank=True, default=3306, null=True),
        ),
    ]
