# Generated by Django 3.2.13 on 2022-08-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0020_auto_20220810_1029'),
        ('helpline', '0020_auto_20220814_1723'),
    ]

    operations = [
    ]
