# Generated by Django 3.2.13 on 2022-10-06 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpline', '0021_merge_0020_auto_20220810_1029_0020_auto_20220814_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backendservermanagerconfig',
            name='mysql_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='backendservermanagerconfig',
            name='mysql_user',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('ip_address', models.GenericIPAddressField()),
                ('comment', models.CharField(blank=True, max_length=80, null=True)),
                ('banned', models.BooleanField(default=False)),
                ('user_data', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
