# Generated by Django 3.2.13 on 2022-10-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0023_clock_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdesk',
            name='turn_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TURN Password'),
        ),
        migrations.AddField(
            model_name='hotdesk',
            name='turn_uri',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TURN URI'),
        ),
        migrations.AddField(
            model_name='hotdesk',
            name='turn_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TURN Username'),
        ),
    ]
