# Generated by Django 3.2.13 on 2022-10-21 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpline', '0024_auto_20221021_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnServerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('turn_uri', models.CharField(max_length=253)),
                ('turn_username', models.CharField(max_length=253)),
                ('turn_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotdesk',
            name='turn_password',
        ),
        migrations.RemoveField(
            model_name='hotdesk',
            name='turn_uri',
        ),
        migrations.RemoveField(
            model_name='hotdesk',
            name='turn_username',
        ),
        migrations.AddField(
            model_name='hotdesk',
            name='turn_server',
            field=models.ForeignKey(blank=True, help_text='TURN Server', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpline.turnserverconfig'),
        ),
    ]
